version: '3'

volumes:
  pg_data_prod:
  static_prod:
  media_prod:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_prod:/var/lib/postgresql/data

  backend:
    image: alexya56/kittygram_backend
    env_file: .env
    volumes:
      - static_prod:/backend_static/
      - media_prod:/app/media/

  frontend:
    image: alexya56/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_prod:/frontend_static
      
  gateway:
    image: alexya56/kittygram_gateway
    env_file: .env
    volumes:
      - static_prod:/staticfiles/
      - media_prod:/media/
    ports:
      - 9000:80
